apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress-test
  name: ingress-test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ingress-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        restart.k8s.hpa.de/ttl: 5m
      labels:
        app: ingress-test
    spec:
      initContainers:
      - name: init-sleep
        image: busybox
        command: ["sleep", "10"]
      containers:
      - image: hashicorp/http-echo
        imagePullPolicy: Always
        name: http-echo
        resources: {}
