apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-deployment
  name: argo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argo-deployment
    spec:
      containers:
      - image: hashicorp/http-echo
        imagePullPolicy: Always
        name: http-echo
        resources: {}
